;Memory offsets
	#module "memory/work.asm"
	#module "memory/pl_mem.asm"



;##############################################
;Programming Modules
	#module "build/bank01.asm"
	#module "build/bank02.asm"
	#module "build/bank03.asm"
	#module "build/bank04.asm"
	#module "build/bank05.asm"
	#module "build/bank06.asm"
	#module "build/bank07.asm"
	#module "build/bank08.asm"
	#module "build/bank09.asm"
	#module "build/bank0a.asm"
	#module "build/bank0b.asm"
	#module "build/bank0c.asm"
	#module "build/bank0d.asm"
	#module "build/bank0e.asm"
	#module "build/bank0f.asm"
	#module "build/bank10.asm"
	#module "build/bank11.asm"
	#module "build/bank12.asm"
	#module "build/bank13.asm"
	#module "build/bank14.asm"
	#module "build/bank15.asm"
	#module "build/bank16.asm"
	#module "build/bank17.asm"
	#module "build/bank18.asm"
	#module "build/bank19.asm"
	#module "build/bank1a.asm"
	#module "build/bank1b.asm"
	#module "build/bank1c.asm"
